version: '3'
services:
 redis:
   image: redis:alpine
   hostname: redis
   volumes:
       - ./redis.conf:/usr/local/etc/redis/redis.conf
       - redis_data:/data
   ports:
     - "6379:6379"
   networks:
     - redis-cluster

# redmon:
#   image: vieux/redmon
#   links:
#     - "redis"
#   ports:
#     - "4567:4567"
#   networks:
#     - redis-cluster
#   command: -r redis://redis:6379

# rebrow:
#   image: marian/rebrow
#   links:
#     - "redis"
#   ports:
#     - "5001:5001"
#   networks:
#     - redis-cluster

volumes:
 redis_data:
   driver: local

networks:
 redis-cluster:
   driver: bridge