version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
     - rabbitmq-cluster
    environment:
     - RABBITMQ_ERLANG_COOKIE=cluster_cookie
     - RABBITMQ_DEFAULT_USER=tuzel-rb-admin
     - RABBITMQ_DEFAULT_PASS=Netas2018

networks:
  rabbitmq-cluster:
    driver: bridge